### ISSUE TITLE
Try to mitigate v1.0.0 release

### ISSUE THREAD

**Issue by ccoVeille** [ccoVeille/go-safecast#24]
v1.0.0 was published too fast.

The code was not definitive, I should have used a v0.1.0 not a v1.0.0

Also, the release was published without the pre-release status on GitHub

![2024-09-08_10-21](https://github.com/user-attachments/assets/31b4ed16-d5c4-4ca0-b5ec-82ac95138cc5)

**Comment by ccoVeille** [comment]
Here I plan to try using https://go.dev/ref/mod#go-mod-file-retract

**Comment by ccoVeille** [comment]
it worked https://pkg.go.dev/github.com/ccoveille/go-safecast@v1.0.0

**Comment by ldemailly** [comment]
yup (commented in other pr) but... you made 1.1.0 (tag) but not (yet) the release notes for that tag
