### ISSUE TITLE
code climate is not updated on merge

### ISSUE THREAD

**Issue by ccoVeille** [ccoVeille/go-safecast#27]
Code climate reports an error https://codeclimate.com/github/ccoVeille/go-safecast

![image](https://github.com/user-attachments/assets/23a4d29f-0ef9-4e8c-900d-e9be2abdb347)

I should consider adding Code Climate to github/workflows/coverage.yml, the same way I did for codecov

**Comment by ldemailly** [comment]
seems to be working upload side https://github.com/ccoVeille/go-safecast/actions/runs/10754914798/job/29826028513

but I've had issue with codecov, tokens etc...

**Comment by ccoVeille** [comment]
Fixed

![image](https://github.com/user-attachments/assets/8d6bb5b8-efef-46e4-afd1-1e3c940b01ff)
